spring:
  graphql:
    graphiql:
      enabled: true
    schema:
      printer:
        enabled: true
  config:
    import: optional:file:.env[.properties]
  cloud:
    openfeign:
      client:
        config:
          euxpApi:
            connect-timeout: 3000
          smdApi:
            connect-timeout: 3000
          scsApi:
            connect-timeout: 48000


env:
  API_KEY: ${API_KEY}
  AUTH_VAL: ${AUTH_VAL}
  CLIENT_ID: ${CLIENT_ID}
  TIMESTAMP: ${TIMESTAMP}
  TRACE: ${TRACE}
  UUID: ${UUID}
  EUXP_URL: ${EUXP_URL}
  SMD_URL: ${SMD_URL}
  SCS_URL: ${SCS_URL}
logging:
  level:
    com.skb.ft.synopsisservice.domain: DEBUG
    org.apache.tomcat: INFO
    org.apache.tomcat.util.net: WARN

