spring:
  graphql:
    graphiql:
      enabled: true
    schema:
      printer:
        enabled: true
  config:
    import: optional:file:.env[.properties]

env:
  API_KEY: ${API_KEY}
  AUTH_VAL: ${AUTH_VAL}
  CLIENT_ID: ${CLIENT_ID}
  TIMESTAMP: ${TIMESTAMP}
  TRACE: ${TRACE}
  UUID: ${UUID}